### ISSUE TITLE
Membership of the Steering Council

### ISSUE THREAD

**Issue by tdhu** [opendatacube/governance#3]
Hi All

I think it would be good if the initial Steering Council include more people who were actively developing the code (to complement people like myself who aren't). I've included the current list of proposed names below for reference and I wonder if there is the ability to add a couple more people from AMA, GA and CSIRO. For example, from GA I'd have thought @andrewdhicks, @GypsyBojangles  @jeremyh would be great contributors and able to actively engage. From the list of members that I can see, I wonder if @axman6, @caffeine-potent (forgive my git ignorance if I'm missing other obvious names) might also be available? Conscious we don't want to load up with too many people, but I'm not convinced that we have the balance quite right at the moment.

The current list is:
Trevor Dhu, @tdhu
Simon Oliver, @simonaoliver
Rob Woodcock, @woodcockr
Brian Killough,
Damien Ayers, @omad
Sanjay Gowda, @sgowda1
Andrew Cherry, @AMA-AC

**Comment by woodcockr** [comment]
I'm very hesitant with large councils, it is difficult for people to contribute effectively to discussion when they get unwieldy.

It is also worth remembering there are sub-project committees that need membership as well for different modules that serve similar functions to the Steering Council but closer to that module - actively developing that code. The principle was to delegate decisions as far down as possible and only to escalate when the need arises to get out of the focus on a specific module. A large Steering Council seems to go counter to this principle of having an alternative perspective and more over, seems to be creating extra duties.

I think I'd rather see the sub-project committees populated first before making a decision to expand the Steering Council to a lot of people.

**Comment by alexgleith** [comment]
This issue is no longer relevant.
