### ISSUE TITLE
@alexgleith to write up an approach to the repo for v2.0

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/governance#30]
(shared v2.0 development branch, separate from the develop branch).

**Comment by woodcockr** [comment]
Have converted this SC Action into an issue so it can support discussion.

CSIRO developments on the roadmap to datacube-core v2 have reached a stage of requiring a v2 develop branch - or more correctly, a branch from v2 develop which can later be merged in with contributions from other ODC community members.

I'm going to kick off a v2 branch in datacube-core and advice CSIRO developments branch from that. This should minimize confusion whilst this SC action is resolved more fully. It may even simply be resolved by doing this.

**Comment by SpacemanPaul** [comment]
Fait accompli.
