### ISSUE TITLE
Identify sub-project committee memberships

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/governance#4]
One of the principles discussed in the governance of the ODC is that decisions be made as close as possible to those teams of people who are contributing to any given component (be it code, documentation, design). In the newly minted Governance structure the Steering Council can set up such sub-project committees for this purpose with the Steering Council itself only need to deal with any cross-cutting, interface or deadlock situation that a sub-project committee can't, by nature of its narrower focus, deal with. Similarly, it means the Steering Council doesn't deal with details in modules it can't deal with.

At the moment the [Components and Interfaces](https://github.com/opendatacube/documentation/blob/master/Components%20and%20Interfaces.md) are still being discussed so we don't know what the sub-projects are in all cases. The current repository layout does have a few (datacube.core, governance).

An activity is required for the Steering Council to formalise:
1. The Components and Interfaces adhoc sub-project so that work can be completed
2. The more permanent sub-project committees for the identified components including the whitepaper, communications, documentation, datacube-core, architecture stewardship, etc identified at the CEOS Data Cube Workshop on the 3rd March

**Comment by alexgleith** [comment]
Closing this as it's very old!
